specification/library-guidelinesを追加
open-telemetry/docs-ja pull request #32
Opened 2020-06-06 07:12 UTC by shirou

- 辞書
も追加

2020-06-07 11:42 UTC, ymotongpoo requested changes
早速のコミットありがとうございます。気になった点、修正が必要と思われた点をコメントしました。
またまだ翻訳が終わってない部分がありましたが、タイトルにWIPがついたPRですし、そちらは今後のコミットで修正されるという認識でいいですよね？

2020-06-07 11:42 UTC, ymotongpoo commented on dictonary.md
> +  - ??? とりあえずSpan
「上では英語のママとする」と書いているけれど、ここで???になっているのはなにか理由がありますか

2020-06-07 11:42 UTC, ymotongpoo commented on dictonary.md
> +  - ??? とりあえずTracer
OpenTelemetry用語なので、基本原則に従うならTracerで良いと思います。

2020-06-07 11:42 UTC, ymotongpoo commented on dictonary.md
> +  - Telemetry exporter???
テレメトリーは一般用語だと思うので「テレメトリー」で良いと思います。続くExporterですが、OpenTelemetry用語として良いと思うので、基本原則に従うのであれば「テレメトリーExporter」になると思います。

2020-06-07 11:42 UTC, ymotongpoo commented on dictonary.md
> +  - expoter
英単語をそのままで使う場合、大文字始まりか小文字始まりかは統一したほうが良いと思います。
これまでの訳出を見ると大文字始まりにしたほうが良いと思います。

2020-06-07 11:42 UTC, ymotongpoo commented on dictonary.md
> +  - テレメトリデータ
基本原則に従うのであれば「テレメトリー」になると思います。

2020-06-07 11:42 UTC, ymotongpoo commented on specification/library-guidelines.md
> +# OpenTelemetryにおける、言語ライブラリのデザイン原則
ソフトウェアエンジニアリングの文脈ではdesignは「デザイン」よりも「設計」のほうが一般的なような気がしますがどうでしょうか

2020-06-07 11:42 UTC, ymotongpoo commented on specification/library-guidelines.md
> +2. 機能を提供するサードパーティのライブラリとフレームワークは、OpenTelemetryの言語ライブラリAPIのみに依存します。サードパーティライブラリとフレームワークの開発者は、最終的なアプリケーションでOpentelemetryのどの実装が使われているかを気にしません(そして知ることもできません)。
Opentelemetry → OpenTelemetry

2020-06-07 11:42 UTC, ymotongpoo commented on specification/library-guidelines.md
> +3. 通常、最終的なアプリケーションの開発者がOpenTelemetry SDK をどのように設定し、どのような拡張機能を使用するかを決めます。彼らはそのアプリケーションやライブラリがすでにOpenTelemetryを実装しているにも関わらずその実装を全く使わないこともできます(???)。これは、OpenTelemetryが実装されたサードパーティのライブラリやフレームワークは、OpenTele
instrument → 計装、インストルメントする

OpenTelemetryを実装しているにも関わらず→OpenTelemetryを使って計装していたとしても

2020-06-07 11:42 UTC, ymotongpoo commented on specification/library-guidelines.md
> +5. SDK実装は以下のexporterを含まなければいけません:
MUST、SHOULDなどの助動詞は原文でBCP14に従うと[明記している](https://github.com/open-telemetry/opentelemetry-specification/blob/v0.4.0/README.md#notation-conventions-and-compliance)ので、訳出もそれに従ってください。（現状ではMUSTとの違いが不明瞭です。）
c.f. http://www.cam.hi-ho.ne.jp/mendoxi/rfc/rfc2119j.html

2020-06-07 11:42 UTC, ymotongpoo commented on specification/library-guidelines.md
> +    他のベンダー依存のexporeter(ベンダー独自のプロトコルを実装しているexporter)は言語ライブラリに含まれるべきではありませんし、他の場所に置かれるべきです(ベンダー依存のexporterを置く正確な場所は将来定義される予定です)
exporeter → exporter （頭の大文字化は別）

2020-06-07 11:42 UTC, ymotongpoo commented on specification/library-guidelines.md
> +OpenTelemetryと互換性がある方法で計測したいサードパーティのライブラリとフレームワークはAPIパッケージに依存します。これらサードパーティのライブラリの開発者はテレメトリデータを作成するためにテレメトリAPIの呼び出しを追加します。
計測→計装

計測（する）はmeasurement (measure) などに当てられる訳になります。

2020-06-07 11:42 UTC, ymotongpoo commented on specification/library-guidelines.md
> +OpenTelemetry APIで計測されるサードパーティライブラリを使うアプリケーションはテレメトリデータを実際に送信するかしないかを決めることができます。アプリケーションは追加のテレメトリデータを作成するためにテレメトリAPIを直接呼ぶこともできます。
計測→計装
テレメトリ→テレメトリー

2020-06-07 11:42 UTC, ymotongpoo commented on specification/library-guidelines.md
> +テレメトリを有効にするためにアプリケーションはテレメトリを配信する機能を実装したOpenTelemetry SDKへの依存が必要です。また、アプリケーションはテレメトリをどこにどうやって送信するかをexporterに設定する必要があります。どのようにexporterを有効化し、設定するかは言語によって異なります。
テレメトリ→テレメトリー

2020-06-07 11:42 UTC, ymotongpoo commented on specification/library-guidelines.md
> +APIパッケージは自己完結型の依存関係にあり、エンドユーザーアプリケーションやサードパーティーライブラリがAPIパッケージだけに依存し、完全なSDK実装に依存しない場合でも、アプリケーションはビルドも実行も失敗しませんが、テレメトリデータは実際にテレメトリバックエンドに配信されません。(???)
「SDKを使っていなければバックエンドにはデータは送信されないけれども、使わなくても軽装されたもののビルドは可能になる」ということを説明しています。

2020-06-07 11:42 UTC, ymotongpoo commented on specification/library-guidelines.md
> +自己完結型は以下の方法によって実現されます。
型→性

2020-06-07 11:42 UTC, ymotongpoo commented on specification/library-guidelines.md
> +API 依存関係には、API の最小実装が含まれています。他の実装がアプリケーションに明示的に含まれていない場合、テレメトリデータは収集されません。この場合のアクティブなコンポーネントは以下のようになります。
テレメトリ→テレメトリー

2020-06-07 11:42 UTC, ymotongpoo commented on specification/library-guidelines.md
> +また、OpenTelemetryで計測されたサードパーティのフレームワークやライブラリが、OpenTelemetryを使用したくないライブラリのユーザに無視できるほどのオーバーヘッドを課すことがないように、最小限の実装で可能な限りパフォーマンスのペナルティが発生しないようにすることも重要です。
計測→計装

2020-06-07 11:42 UTC, ymotongpoo commented on specification/library-guidelines.md
> +### SDK 実装
次のコミットで以下は翻訳される予定ですか？

2020-06-07 11:42 UTC, ymotongpoo commented on specification/library-layout.md
> +このディレクトリはアプリケーションとライブラリのコードを提供します。
privateの訳出がありません

2020-06-07 11:42 UTC, ymotongpoo commented on specification/library-layout.md
> +このリソースディレクトリはあるエンティティについて状態あるいはトレースの情報を取得するかを示す [Resource](overview.md#resources) 型を定義します。
「どのStatsあるいはTraceが記録されたかに関するエンティティに関する情報を記録するResource型」

2020-06-07 13:58 UTC, shirou commented
ありがとうございます！
はい、訳す文書の重複を避けるために早めにPRを出しただけで、まだまだ途中です。一通り終わったあとに改めてreview依頼を出そうと考えていました。意図を説明していなくてすいません。

でも、このタイミングでコメントを頂けたのでそれに沿って続く文章も訳していきたいと思います。

2020-06-07 14:08 UTC, shirou commented on specification/library-guidelines.md
> +5. SDK実装は以下のexporterを含まなければいけません:
その明記部分で"when, and only when, they appear in all capitals, as shown here."とあり、 Requirement Levelを示すものは "MUST" や "SHOULD" などすべて大文字(all capitals)で書くと書かれているため、ここはそのrequirement levelを示すものではない、という理解だったのですが、約し分けたほうがいいでしょうか。(IETFのRFCもrequirement levelを示す場合はoftenと書かれていますが基本的にAll capitalsで書くという理解です)

2020-06-09 13:59 UTC, ymotongpoo requested changes
丁寧な訳で非常に読みやすかったです。一点だけtypoがあったので、そこだけ指摘しました。

2020-06-09 13:59 UTC, ymotongpoo commented on specification/library-guidelines.md
> +4. SDK は、(バッチ、タグへのプロセス情報の追加など)共通のロジックを実装するワイヤプロトコルに依存しない部分と、プロトコルに依存したテレメトリーのエクスポートを行う部分とに明確に分離されている必要があります(MUST)。テレメトリー exporterは最低限の機能のみを持たなければならず(MUST)、これによりベンダーが特定のプロトコルのサポートを簡単に追加できるようになっています。
テレメトリーexporter → テレメトリーExporter

2020-06-09 14:42 UTC, shirou commented on specification/library-guidelines.md
> +4. SDK は、(バッチ、タグへのプロセス情報の追加など)共通のロジックを実装するワイヤプロトコルに依存しない部分と、プロトコルに依存したテレメトリーのエクスポートを行う部分とに明確に分離されている必要があります(MUST)。テレメトリー exporterは最低限の機能のみを持たなければならず(MUST)、これによりベンダーが特定のプロトコルのサポートを簡単に追加できるようになっています。
ありがとうございます。修正しました！

2020-06-10 00:55 UTC, ymotongpoo approved these changes
ありがとうございました！LGTM!

2020-06-10 00:56 UTC, merged