Add speficiation/protocol
open-telemetry/docs-ja pull request #37
Opened 2020-06-13 09:44 UTC by shirou

- Closes #24 spec: protocol/README
- Closes #25 spec: protocol/design-goals
- Closes #26  spec: protocol/requirements

量が少なかったので一つのPRにまとめました。

2020-06-18 12:17 UTC, ymotongpoo requested changes
全体的な翻訳は読みやすかったです。訳語の統一に関していくつか細かい指摘をしたのと、1点翻訳表現の修正をお願いします。

2020-06-18 12:17 UTC, ymotongpoo commented on specification/protocol/design-goals.md
> +- 以下のすべてのノードの種類に適していること: アプリケーションへの計装、テレメトリーバックエンド、ローカルエージェント、スタンドアローン collector/forwarder。
英語をそのまま使う場合は大文字始まりで統一するのが良いと思います。

2020-06-18 12:17 UTC, ymotongpoo commented on specification/protocol/design-goals.md
> +- デシリアライズされたデータを効率的に修正し、さらに別なところに渡すために再度シリアライズする機能をサポートすること。関連はありますが、上記の要件とは少し異なります。
efficiently は modify と serialize の両方にかかっているので、それが明確になるように訳してください。

2020-06-18 12:17 UTC, ymotongpoo commented on specification/protocol/requirements.md
> +以下のすべてのノードの種類をサポートすること(MUST): アプリケーションへの計装、テレメトリーバックエンド、ローカルエージェント、スタンドアローン collector/forwarder。
design-goals.md と同様、英語は大文字始まりに統一したほうが良いと思います。

2020-06-18 12:17 UTC, ymotongpoo commented on specification/protocol/requirements.md
> +注意: このプロトコルは、一対のクライアント/サーバ間の送信の信頼性に着目しており、クライアントとサーバ間の転送中にデータが失われることがないことを目的としています。多くのテレメトリー収集システムには、最終目的地に到達するまでには複数のノードをデータが移動しなければないけません(例: アプリケーション -> エージェント -> collector -> バックエンド)。このようなシステムにおける
collector → Collector

2020-06-18 12:17 UTC, ymotongpoo commented on specification/protocol/requirements.md
> +使用しているトランスポートが独自のフロー制御メカニズムを持つストリームである場合、サーバのエンドポイントからのデータの読み取りを遅らせることで、トランスポートのフロー制御を介してクライアントに通知して、バックプレッシャーを実現できます。しかし、この方法では、クライアントはサーバの過負荷と(例えばネットワーク切断などによる)ネットワークの遅延を区別することが困難になります。この区別は、[観測性の理
Observabilityは「オブザーバビリティ」にしましょう。（日本語にするなら「可観測性」）

2020-06-19 01:15 UTC, katzchang commented on specification/protocol/requirements.md
> +使用しているトランスポートが独自のフロー制御メカニズムを持つストリームである場合、サーバのエンドポイントからのデータの読み取りを遅らせることで、トランスポートのフロー制御を介してクライアントに通知して、バックプレッシャーを実現できます。しかし、この方法では、クライアントはサーバの過負荷と(例えばネットワーク切断などによる)ネットワークの遅延を区別することが困難になります。この区別は、[観測性の理
オブザーバビリティか可観測性か、どっちかに統一したいとこですね。
オブザーバビリティ、にしてみますか？

2020-06-21 02:52 UTC, shirou commented on specification/protocol/requirements.md
> +使用しているトランスポートが独自のフロー制御メカニズムを持つストリームである場合、サーバのエンドポイントからのデータの読み取りを遅らせることで、トランスポートのフロー制御を介してクライアントに通知して、バックプレッシャーを実現できます。しかし、この方法では、クライアントはサーバの過負荷と(例えばネットワーク切断などによる)ネットワークの遅延を区別することが困難になります。この区別は、[観測性の理
別のところにもコメントしましたが、「可観測性」という訳語がすでに世の中で一定数使われているようですし、日本語の定訳を作る意味でも可観測性に統一するのが良いかと思います。

2020-06-21 02:55 UTC, shirou commented on specification/protocol/design-goals.md
> +- デシリアライズされたデータを効率的に修正し、さらに別なところに渡すために再度シリアライズする機能をサポートすること。関連はありますが、上記の要件とは少し異なります。
結構悩みましたが、
`デシリアライズされたデータを修正し、さらに別なところに渡すために再度シリアライズする効率的な機能をサポートすること`
にしてみました

2020-06-21 13:22 UTC, ymotongpoo approved these changes
effientlyの部分だけ確認です

2020-06-21 13:22 UTC, ymotongpoo commented on specification/protocol/design-goals.md
> +- デシリアライズされたデータを修正し、さらに別なところに渡すために再度シリアライズする効率的な機能をサポートすること。関連はありますが、上記の要件とは少し異なります。
大意を取って「効率的にデータのデシリアライズとその後のデータ転送のシリアライズを行う機能」とagainを省略すると両方にかかるようになると思ったのですがどうでしょうか。

2020-06-21 14:55 UTC, katzchang approved these changes
全体的に、読みやすい感じでよかったです。

2020-06-22 02:58 UTC, shirou commented on specification/protocol/design-goals.md
> +- デシリアライズされたデータを修正し、さらに別なところに渡すために再度シリアライズする効率的な機能をサポートすること。関連はありますが、上記の要件とは少し異なります。
なるほど。ありがとうございます！そうしてみます。

2020-06-25 07:17 UTC, merged